import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import { axiosInstance } from '../helpers/axiosHelper';

const inter = Inter({ subsets: ['latin'] })

export default function Login() {
  const LoggingIn = () => {
    // @ts-ignore: Object is possibly 'null'
    const email = document.getElementById('email').value
    // @ts-ignore: Object is possibly 'null'
    const password = document.getElementById('password').value

    console.log(email);

    if (email != '' && password != ''){
      axiosInstance.post('/auth/login',{
        "username": email,
        "password": password
      }).then(response=>{
        console.log(response);
      })
    }
  }
  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='container'>
        <p className='text-2xl text-center mt-10 mb-5'>Login</p>
        <div className="max-w-sm p-6 bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700 mx-auto">
          <div className="mb-6">
            <label htmlFor="email" className="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Your email</label>
            <input type="email" id="email" className="base_input" placeholder="name@flowbite.com" required />
          </div>
          <div className="mb-3">
            <label htmlFor="password" className="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Your password</label>
            <input type="password" id="password" className="base_input" required/>
          </div>
          <div className='mb-6'>
            <a className="underline decoration-sky-500" href="/sign_up">register now</a>
          </div>
          <button onClick={()=>LoggingIn()} type="submit" className="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Log in</button>
        </div>
      </main>
    </>
  )
}